name: CI - BUILD

on: [ pull_request ]

jobs:

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker build
        run: docker build -t valmirphp/node-puppeteer-docker -f Dockerfile .

      - name: Docker list images
        run: docker images
